# syntax=docker/dockerfile:1
FROM node:14.15.4-slim
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --development
COPY . .
RUN npm run build
CMD [ "npm", "run", "start:dev"]